// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Urlize_back.Models;

#nullable disable

namespace Urlize_back.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240422224744_migrationjihen2")]
    partial class migrationjihen2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Urlize_back.Models.Business", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("brandDescription")
                        .HasColumnType("int")
                        .HasColumnName("brandDescription");

                    b.Property<string>("businessName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Name");

                    b.Property<int?>("categorie")
                        .HasColumnType("int")
                        .HasColumnName("categorie");

                    b.Property<int>("colorPalette")
                        .HasColumnType("int")
                        .HasColumnName("colorPalette");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<int>("designPref")
                        .HasColumnType("int")
                        .HasColumnName("designPref");

                    b.Property<int>("goal")
                        .HasColumnType("int")
                        .HasColumnName("goal");

                    b.Property<string>("logo_url")
                        .HasColumnType("longtext")
                        .HasColumnName("logo");

                    b.HasKey("Id");

                    b.ToTable("Business");
                });

            modelBuilder.Entity("Urlize_back.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Available")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("Available");

                    b.Property<string>("Description")
                        .HasColumnType("longtext")
                        .HasColumnName("Description");

                    b.Property<string>("Image")
                        .HasColumnType("longtext")
                        .HasColumnName("Image");

                    b.Property<string>("Name")
                        .HasColumnType("longtext")
                        .HasColumnName("Name");

                    b.Property<float>("Price")
                        .HasColumnType("float")
                        .HasColumnName("Price");

                    b.Property<int>("businessId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("businessId");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("Urlize_back.Models.Product", b =>
                {
                    b.HasOne("Urlize_back.Models.Business", "business")
                        .WithMany("product")
                        .HasForeignKey("businessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("business");
                });

            modelBuilder.Entity("Urlize_back.Models.Business", b =>
                {
                    b.Navigation("product");
                });
#pragma warning restore 612, 618
        }
    }
}
